[package]
name = "tokio-example"
version = "0.1.0"
authors = ["Luke Steensen <luke.steensen@gmail.com>"]

[dependencies]
futures = "0.1"
tokio-core = "0.1"
tokio-proto = { git = "https://github.com/tokio-rs/tokio-proto" }
tokio-service = { git = "https://github.com/tokio-rs/tokio-service" }
